name: Generate JSDoc Documentation

on:
  push:
    branches:
      - main
      - CI/CD-pipeline
      - Documentation-Generate

jobs:
  build-docs:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "v16.18.0"

      - name: Install dependencies
        run: npm install

      # - name: Build
      #   uses: andstor/jsdoc-action@v1
      #   with:
      #     source_dir: ./test
      #     recurse: true
      #     output_dir: ./out
      #     config_file: jsdoc.config.json
      #     template: clean-jsdoc-theme

      - name: Generate Documentation
        run: npx jsdoc -c jsdoc.config.json

      - name: Commit and Push Documentation
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add docs/
          git commit -m "Update documentation"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}

      # - name: Setup Git Identity
      #   run: |
      #     git config --local user.name 'GitHub Actions'
      #     git config --local user.email 'actions@github.com'

      # - name: Commit Documentation
      #   run: |
      #     git add docs/
      #     git commit -m "Update documentation" || echo "No changes to commit"
      #     git push
